version: "3"
services:
  centosmachine:
    container_name: centosmachine
    image: centosmachine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /opt/practice/dockervolume:/opt/practice
    # For autosuggestions
    - /opt/practice/.zsh_history:/root/.zsh_history
    networks:
    - net
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - 8082:8080
    volumes:
    - /opt/practice/jenkins-volume:/var/jenkins_home
    networks:
    - net
  slave:
    container_name: slave
    image: slave
    build:
      context: .
      dockerfile: Dockerfile-slave
    volumes:
    - /opt/practice/jenkins-volume/jenkins-slave-workspace:/opt/jenkins-slave-workspace
    - ${PWD}/utilities/ssh-keys/ansible-user-key.pub:/home/jenkins/.ssh/authorized_keys
    networks:
    - net
  dockerslave:
    container_name: dockerslave
    image: dockerslave
    build:
      context: .
      dockerfile: Dockerfile-docker-slave
    privileged: true
    volumes:
    - dind_data:/var/lib/docker
    networks:
    - net
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: unless-stopped
    environment:
    - SONARQUBE_JDBC_USERNAME=sonarqube
    - SONARQUBE_JDBC_PASSWORD=sonarpass
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
    - net
  db:
    container_name: sonar-pgdb
    image: postgres
    restart: unless-stopped
    environment:
    - POSTGRES_USER=sonarqube
    - POSTGRES_PASSWORD=sonarpass
    - POSTGRES_DB=sonarqube
    volumes:
    - sonarqube_db:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
    networks:
    - net
volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
  dind_data:
networks:
  net: