version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - 8082:8080
    volumes:
    -  jenkins_master:/var/jenkins_home
    networks:
    - net
  slave:
    container_name: slave
    image: slave
    build:
      context: .
      dockerfile: Dockerfile-slave
    volumes:
    -  jenkins_slave:/opt/jenkins-slave-workspace
    networks:
    - net
  dockerslave:
    container_name: dockerslave
    image: dockerslave
    build:
      context: .
      dockerfile: Dockerfile-docker-slave
      args:
        DOCKER_GID: ${DOCKER_GID:-999}
    privileged: true
    volumes:
    - dind_data:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - net
volumes:
  dind_data:
  jenkins_master:
  jenkins_slave:
networks:
  net: