FROM centos:7

# Set environment variables
# Java home is optional but maven home is required
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk
ENV MAVEN_HOME /usr/share/maven
ENV PATH ${PATH}:${JAVA_HOME}/bin:${MAVEN_HOME}/bin

RUN yum update -y && \
# Install utilities
    yum install curl wget nano git openssh-server -y  && \
    useradd remote_user && \
    echo "password" | passwd remote_user --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh 
COPY ./utilities/ssh-keys/ansible-user-key.pub /home/remote_user/.ssh/authorized_keys
RUN chown remote_user:remote_user -R /home/remote_user/.ssh && \
    chmod 600 /home/remote_user/.ssh/authorized_keys && \
    /usr/bin/ssh-keygen -A 

# Install maven, It is good idea to combine all statements into single layer single run but for ease of reading I am creating another layer
RUN yum install java-11-openjdk-devel -y && \
    cd /tmp && \
    wget https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz && \
    tar -xzf apache-maven-3.9.3-bin.tar.gz && \
    mv apache-maven-3.9.3 /usr/share/maven && \
    rm -f apache-maven-3.9.3-bin.tar.gz

# Create the Jenkins user
RUN useradd -m -d /home/jenkins -s /bin/bash jenkins 

# Set up SSH
RUN mkdir /var/run/sshd
RUN echo "jenkins:jenkins" | chpasswd
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config

# Add SSH public key for Jenkins user
RUN mkdir /home/jenkins/.ssh
RUN chown jenkins:jenkins /home/jenkins/.ssh
RUN chmod 700 /home/jenkins/.ssh
COPY ./utilities/ssh-keys/ansible-user-key.pub /home/jenkins/.ssh/authorized_keys
RUN chown jenkins:jenkins /home/jenkins/.ssh/authorized_keys
RUN chmod 600 /home/jenkins/.ssh/authorized_keys

# Jenkins slave configuration
RUN mkdir -p /opt/jenkins-slave-workspace && \
chown -R jenkins:jenkins /opt/jenkins-slave-workspace

EXPOSE 22
RUN rm -rf /run/nologin
CMD /usr/sbin/sshd -D